- name: Backup original scylla.yaml
  copy:
    src: /etc/scylla/scylla.yaml
    dest: /etc/scylla/scylla.yaml.bak
    remote_src: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Deploy updated scylla.yaml config
  template:
    src: scylla.yaml.j2
    dest: /etc/scylla/scylla.yaml
    owner: scylla
    group: scylla
    mode: '0644'
  become: true

- name: Start Scylla
  service:
    name: scylla-server
    enabled: yes
    state: started


- name: Ensure scylladb user exists with password
  ansible.builtin.user:
    name: scylladb
    password: "{{ 'password' | password_hash('sha512') }}"
    shell: /bin/bash
    comment: "ScyllaDB User"
    state: present



- name: Create keyspace, user, and table
  shell: |
    echo "
    cqlsh  {{ ansible_host }} -u {{ scylla_user }} -p {{ scylla_pass }}
    CREATE USER  {{ scylla_app_user }}  WITH PASSWORD  {{ scylla_app_password }} SUPERUSER;
    GRANT ALL PERMISSIONS ON ALL KEYSPACES TO {{ scylla_app_user }};
    CREATE KEYSPACE IF NOT EXISTS employee_DB WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
    USE employee_DB;
    CREATE TABLE IF NOT EXISTS employee_salary (
      id text,
      process_date text,
      name text,
      salary float,
      status text,
      PRIMARY KEY (id, process_date)
    ) WITH CLUSTERING ORDER BY (process_date DESC);"
