---
- name: Install Java
  include_tasks: install_java.yml

- name: Install Maven
  include_tasks: install_maven.yml

- name: Install Make
  include_tasks: install_make.yml

- name: Install jq
  include_tasks: install_jq.yml

- name: Install Migrate
  include_tasks: install_migrate.yml

- import_tasks: clone_app.yml

- import_tasks: run_api.yml

