- name: Run database migrations
  command: make migrate
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: "{{ app_user }}"

- name: Start the Salary API
  command: make run
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: "{{ app_user }}"

