- name: src/main application
  template:
    src: application.yml.j2
    dest: "{{ app_dir }}/src/main/resources/application.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'

- name: src/test application
  template:
    src: applicationtest.yml.j2
    dest: "{{ app_dir }}/src/test/resources/application.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'

- name: Render migration.json with DB config
  template:
    src: migration.json.j2
    dest: "{{ app_dir }}/migration.json"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'

      #- name: Run database migrations
      #command: make run-migrations
      #args:
      #chdir: "{{ app_dir }}"
      #become: yes
      #become_user: "{{ app_user }}"

- name: Run migrations
  command: /usr/bin/gmake run-migrations
  args:
    chdir: /home/ubuntu/salary-api

- name: Start the Salary API
  command: make build
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: "{{ app_user }}"

- name: java release
  command: java -jar target/salary-0.1.0-RELEASE.jar
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_user: "{{ app_user }}"
